"""
Optimization brief template
"""

BRIEF_TEMPLATE = """# SEO Content Optimization Brief

## Target Page
- **URL:** {url}
- **Target Keyword:** {keyword}
- **Current Health Score:** {health_score:.0f}/100
{previous_score_line}

---

## Priority Actions

{priority_actions}

---

## Content Requirements

### Word Count
- **Current:** {client_word_count:,} words
- **Competitor Average:** {competitor_avg_word_count:,.0f} words
- **Recommended:** {recommended_min:,} - {recommended_max:,} words

### Entities to Add (Missing)
These semantic concepts appear in top competitors but are absent from your page:

{missing_entities_section}

### Entities to Strengthen (Weak)
These appear on your page but with less emphasis than competitors:

{weak_entities_section}

---

## Heading Structure

### Current Structure
{client_headings_section}

### Recommended Changes
{heading_recommendations}

---

## Writing Style

{style_section}

---

## Additional Recommendations

{additional_recommendations}

---

## Brand Phrases to Preserve
{brand_phrases_section}

---

## Competitor Summary
{competitor_summary}

---

*Generated by EntScore | Analysis completed in {duration:.1f}s | API cost: ${cost:.4f}*
"""


def format_priority_actions(actions: list) -> str:
    """Format priority actions for the brief."""
    if not actions:
        return "No major optimization opportunities detected."

    lines = []
    for i, action in enumerate(actions, 1):
        priority = action.get("priority", "MEDIUM")
        lines.append(f"{i}. **[{priority}]** {action['action']}")
        lines.append(f"   - {action['reason']}")
    return "\n".join(lines)


def format_entity_list(entities: list, status: str) -> str:
    """Format entity list for the brief."""
    filtered = [e for e in entities if e.get("gap_status") == status]
    if not filtered:
        return f"No {status} entities found."

    lines = []
    for ent in filtered[:15]:  # Cap at 15
        freq = ent.get("competitor_frequency", 0)
        lines.append(f"- **{ent['entity_text']}** (in {freq}/10 competitors)")
    return "\n".join(lines)


def format_headings(headings: list) -> str:
    """Format heading list for the brief."""
    if not headings:
        return "No headings found on the page."

    lines = []
    for h in headings:
        indent = "  " * (int(h["level"][1]) - 1)
        lines.append(f"{indent}- {h['level'].upper()}: {h['text']}")
    return "\n".join(lines)
